Webgentle.BookStore/Webgentle.BookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Webgentle.BookStore.Models;
using Webgentle.BookStore.Repository;

namespace Webgentle.BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository = null;
        private readonly ILanguageRepository _languageRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BookController(IBookRepository bookRepository,
            ILanguageRepository languageRepository,
            IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _languageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [Route("all-books")]
        public async Task<ViewResult> GetAllBooks()
        {
            var data = await _bookRepository.GetAllBooks();

            return View(data);
        }

        [Route("book-details/{id:int:min(1)}", Name = "bookDetailsRoute")]
        public async Task<ViewResult> GetBook(int id)
        {
            var data = await _bookRepository.GetBookById(id);

            return View(data);
        }

        public List<BookModel> SearchBooks(string bookName, string authorName)
        {
            return _bookRepository.SearchBook(bookName, authorName);
        }

        [Authorize]
        public async Task<ViewResult> AddNewBook(bool isSuccess = false, int bookId = 0)
        {
            var model = new BookModel();

            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
            if (ModelState.IsValid)
            {
                if (bookModel.CoverPhoto != null)
                {
                    string folder = "books/cover/";
                    bookModel.CoverImageUrl = await UploadImage(folder, bookModel.CoverPhoto);
                }

                if (bookModel.GalleryFiles != null)
                {
                    string folder = "books/gallery/";

                    bookModel.Gallery = new List<GalleryModel>();

                    foreach (var file in bookModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadImage(folder, file)
                        };
                        bookModel.Gallery.Add(gallery);
                    }
                }

                if (bookModel.BookPdf != null)
                {
                    string folder = "books/pdf/";
                    bookModel.BookPdfUrl = await UploadImage(folder, bookModel.BookPdf);
                }

                int id = await _bookRepository.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(AddNewBook), new { isSuccess = true, bookId = id });
                }
            }

            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }
    }
}

Webgentle.BookStore/Webgentle.BookStore/Views/Book/AddNewBook.cshtml
@using  Webgentle.BookStore.Enums
@inject Webgentle.BookStore.Repository.ILanguageRepository _languageRepo
@model BookModel
@{
    ViewData["Title"] = "Add new book";
}
<div class="container">
    <h3 class="display-4">Add new book</h3>
    <hr />
    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Congratulations</strong> You have added new book successfully. <br />
            Click <a asp-controller="Book" asp-action="GetBook" asp-route-id="@ViewBag.BookId">here</a> to view the details
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

<form method="post" enctype="multipart/form-data" asp-action="AddNewBook" asp-controller="Book">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="LanguageId" class="control-label"></label>
        <select asp-for="LanguageId" class="form-control" asp-items="(await _languageRepo.GetLanguages()).Select(x=> new SelectListItem() { Text = x.Name, Value = x.Id.ToString()})">
            <option value="">Please choose your language</option>
        </select>
        <span asp-validation-for="LanguageId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author" class="control-label"></label>
        <input asp-for="Author" class="form-control" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TotalPages" class="control-label"></label>
        <input asp-for="TotalPages" class="form-control" />
        <span asp-validation-for="TotalPages" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CoverPhoto" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="CoverPhoto" class="custom-file-input" id="customFile">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
        <span asp-validation-for="CoverPhoto" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GalleryFiles" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="GalleryFiles" class="custom-file-input" id="customFile">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
        <span asp-validation-for="GalleryFiles" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BookPdf" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="BookPdf" class="custom-file-input" id="customFile">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
        <span asp-validation-for="BookPdf" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Add book" class="btn btn-primary" />
    </div>
</form>
</div>

Webgentle.BookStore/Webgentle.BookStore/Views/Book/GetAllBooks.cshtml
@{
    ViewData["Title"] = "All books";
}
@model IEnumerable<BookModel>

<div class="container">
    <h3 class="display-4">All books</h3>
    <div class="row">

        @foreach (var book in Model)
        {
        <div class="col-md-4">
            <partial name="_bookThumbnail" model="@book" />
        </div>
        }

    </div>
</div>

Webgentle.BookStore/Webgentle.BookStore/Views/Book/GetBook.cshtml
@{
    ViewData["Title"] = "Book detail " + Model.Title;
}
@model BookModel


    <div class="container">
        <h3 class="display-4">Book details</h3>
        <div class="row">
            <div class="col-md-6">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">

                        @for (int i = 0; i < Model.Gallery.Count(); i++)
                        {
                            <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i==0 ? "active" : "") "></li>
                        }
                    </ol>
                    <div class="carousel-inner">
                        @for (int i = 0; i < Model.Gallery.Count(); i++)
                        {
                            <div class="@(i==0 ? "carousel-item active" : "carousel-item") ">
                                <img class="d-block w-100" src="@Model.Gallery[i].URL" alt="@Model.Gallery[i].Name">
                            </div>
                        }

                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h1>@Model.Title</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 text-primary">
                        <span class="label label-primary">By: </span>
                        <span class="monospaced">@Model.Author</span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p class="description">
                            @Model.Description
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <a class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal">
                            Read now
                        </a>
                    </div>
                </div>

                <hr />

                <ul class="list-group">
                    <li class="list-group-item"><span class="font-weight-bold">Category - </span> @Model.Category</li>
                    <li class="list-group-item"><span class="font-weight-bold">Total pages - </span> @Model.TotalPages</li>
                    <li class="list-group-item"><span class="font-weight-bold">Language - </span> @Model.Language</li>
                </ul>
            </div>
        </div>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                       @*<embed src="@Model.BookPdfUrl" class="w-100"/>*@
                        <iframe src="@Model.BookPdfUrl" class="w-100"></iframe>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <hr />

        <div class="py-5 bg-light" id="similarBooks">
            <h3 class="h3">Similar books</h3>
            <div class="row">
                @for (int i = 0; i < 5; i++)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                            <div class="card-body">
                                <h3 class="card-title">book.Title</h3>
                                <p class="card-text">book.Description</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-sm btn-outline-secondary">View details</a>
                                    </div>
                                    <small class="text-muted">book.Author</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
